apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rating.fullname" . }}
  labels:
{{ include "rating.labels" . | indent 4 }}
stringData:
  dbconfig.php: |
    <?php
    $dbuser={{ .Values.database.username | squote }};
    $dbpass={{ .Values.database.password | squote }};
    $dbname={{ .Values.database.name | squote }};
    $dbserver={{ .Values.database.server | squote }};
    $dbport={{ .Values.database.port | toString | squote }};
